# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs: 
    - job: Build
      steps:
      - task: ServiceNow-DevOps-Agent-Artifact-Registration@1
        inputs:
          connectedServiceName: 'dev349899-tokuyatakahashi-devops-ServiceNow DevOps Service Connection'
          artifactsPayload: |
            {
              "artifacts": [
                  {
                    "name": "Pipeline1Artifact",
                    "version": "1.$(Build.BuildId)",
                    "semanticVersion": "1.$(Build.BuildId).0",
                    "repositoryName": "Pipeline1Artifact-Repo"
                  }
              ]
            }
      - script: echo "Build"
  - stage: Test
    jobs:
    - job: Unit_Tests 
      steps:
      - task: CmdLine@2
        env:
          SN_DEVOPS_PW: $(SN_DEVOPS_PW)
        inputs:
          script: |
            NOW=$(date +"%Y-%m-%dT%TZ")
            cred=${SN_DEVOPS_USERNAME}:$SN_DEVOPS_PW
            testPayload='{"name":"Test-summary-1.$(Build.BuildId).0","duration":0.0,"passedTests":10,"failedTests":1,"skippedTests":0,"blockedTests":0,"totalTests":11,"startTime":"'$NOW'","finishTime":"'$NOW'","artifacts":[{"name":"Pipeline1Artifact","version":"1.$(Build.BuildId)"}]}'
            echo $testPayload
            curl -X POST 'https://dev349899.service-now.com/api/sn_devops/v1/devops/tool/test?toolId=30d9037d83083210029cad20ceaad334&testType=junit' -H 'Content-Type: application/json' -u $cred -d $testPayload
      - script: echo "Unit Tests"
    - job: Checkmarx_Scan 
      steps:
      - task: CmdLine@2
        env:
          SN_DEVOPS_PW: $(SN_DEVOPS_PW)
        inputs:
          script: |
            NOW=$(date +"%Y-%m-%dT%TZ")
            cred=${SN_DEVOPS_USERNAME}:$SN_DEVOPS_PW
            endpoint=`https://dev349899.service-now.com/api/sn_devops/v1/devops/tool/softwarequality?toolId=$(checkmarxToolId)`
            checmarxPayload='{"scanID": $(Build.BuildId),"scannerName": "Checkmarx","projectName": "app-devops","initiatedBy": "tester@rapdev.io","lastScanned": $NOW,"scanURL": "https://abc.com","shortDescription": "test scan","softwareQualityDetail": [{"category": "vulnerabilities","value": "20","categoryDetail": [{"subcategory": "critical","value": "2"}]},{"category": "license_risks","result": "PASS","expected": "<5","actual": "3"},{"bugs":"3"}],"artifacts": [{"name": "Pipeline1Artifact","version": "1.$(Build.BuildId)"}]}'
            echo $checmarxPayload
            echo $endpoint
            curl -X POST $endpoint -H 'Content-Type: application/json' -u $cred -d $checmarxPayload
      - script: echo "Checkmarx_Scan"  
  - stage: Deploy
    jobs:  
      - job: UAT_Deploy
        steps:
        - task: ServiceNow-DevOps-Agent-Package-Registration@1
          inputs:
            connectedServiceName: 'dev349899-tokuyatakahashi-devops-ServiceNow DevOps Service Connection'
            packageName: 'Pipeline1Package'
            artifactsPayload: |
              {
                "artifacts": [
                {
                    "name": "Pipeline1Artifact",
                    "repositoryName": "Pipeline1Artifact-Repo",
                    "version": "1.$(build.buildId)",
                    "pipelineName":"$(system.teamProject)/$(build.definitionName)",
                    "taskExecutionNumber":"$(build.buildId)",
                    "stageName":"$(system.jobDisplayName)",
                    "branchName":"$(build.sourceBranchName)"
                }],
                "pipelineName":"$(system.teamProject)/$(build.definitionName)",
                "taskExecutionNumber":"$(build.buildId)",
                "stageName":"$(system.jobDisplayName)",
                "branchName":"$(build.sourceBranchName)"
              }
        - script: echo "UAT Deploy"
      - job: Production_Deploy
        steps:
        - script: echo "Production Deploy"
